spring.application.name=MaintenanceRecord
spring.config.import=optional:configserver:http://localhost:8888

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
spring.jpa.show-sql=true

# Retry configuration
resilience4j.retry.instances.MaintenanceRecord-Service.max-attempts=5
resilience4j.retry.instances.MaintenanceRecord-Service.wait-duration=2s

#spring.datasource.url=jdbc:mysql://localhost:3306/maintenance_record
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#server.port=7074